# Generated by Django 5.0 on 2023-12-18 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_bookmark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="is_active",
        ),
    ]
