# Generated by Django 5.0 on 2023-12-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_email_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_token',
        ),
    ]
