# Generated by Django 5.0 on 2023-12-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_remove_customuser_email_verification_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
